# Generated by Django 4.2.16 on 2025-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_new_field_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
